### ISSUE TITLE
Caixa - Para Refletir 

### ISSUE THREAD

**Issue by caroldesanti** [wendellbg/projetomooc#10]
Acrescentar o gif do ícone e título na caixa "para refletir" em:
Corrigir dimensões da caixa em relação ao texto

**UNIDADE 3_ Tela 5**
![09](https://user-images.githubusercontent.com/78487775/106760727-dbeb2f80-6612-11eb-924f-298c1b9019c3.jpg)

**Comment by rogergomes** [comment]
Corrigido o padrão da caixa e inserido o título. Aguardando nova imagem do gif para alterar.

**Comment by rogergomes** [comment]
feito
