### ISSUE TITLE
Rodapé / UNIDADE 3_ Telas 4 e 5 

### ISSUE THREAD

**Issue by caroldesanti** [wendellbg/projetomooc#11]
Padronizar rodapés nas últimas telas da unidade 3
![10](https://user-images.githubusercontent.com/78487775/106760939-1654cc80-6613-11eb-9ebf-8a7ba5649604.jpg)
![11](https://user-images.githubusercontent.com/78487775/106760943-16ed6300-6613-11eb-93b0-b75f092cfa6d.jpg)

**Comment by rogergomes** [comment]
Corrigido.
