### ISSUE TITLE
Slide de imagens/ UNIDADE 3_ Tela 2

### ISSUE THREAD

**Issue by caroldesanti** [wendellbg/projetomooc#12]
Rever uma forma que fique apenas uma seta de cada lado e uma passagem de página abaixo nos slides

![12](https://user-images.githubusercontent.com/78487775/106761230-5f0c8580-6613-11eb-88b0-b8da1dfbe852.jpg)

**Comment by rogergomes** [comment]
Corrigido. Tive que recortar a imagem. Futuramente favor deixar a apenas a imagem (sem o fundo e bordas), pois isso já é inserido pelo código.
