### ISSUE TITLE
Figuras/ UNIDADE 4_ Tela 3 

### ISSUE THREAD

**Issue by caroldesanti** [wendellbg/projetomooc#13]
Retirar figura da criança
![16](https://user-images.githubusercontent.com/78487775/106762178-58cad900-6614-11eb-8a3a-b42aac782ba7.jpg)

Figuras das oficinas não estão aparecendo 
![15](https://user-images.githubusercontent.com/78487775/106762210-5ff1e700-6614-11eb-9062-72827a2c7f68.jpg)

**Comment by rogergomes** [comment]
Corrigido.
