### ISSUE TITLE
Trocar figura/ UNIDADE 4 _ Tela 6

### ISSUE THREAD

**Issue by caroldesanti** [wendellbg/projetomooc#14]
Trocar essa imagem
![18](https://user-images.githubusercontent.com/78487775/106762569-b828e900-6614-11eb-964a-15c4f3a485a8.jpg)

Por essa aqui:
![Infográfico](https://user-images.githubusercontent.com/78487775/106762686-d55db780-6614-11eb-9d14-247cf7724b30.jpg)
[https://drive.google.com/file/d/1SPNHk5uc6ACM75xbHEF21-z1nK6pTXXo/view?usp=sharing](url)

**Comment by rogergomes** [comment]
feito.
