### ISSUE TITLE
Sugestão  Unidade 1 _ tela 5

### ISSUE THREAD

**Issue by stingnelrodrigo** [wendellbg/projetomooc#15]
Na Unidade 1 tela 5 a faixa toda azul ser clicavel em vez de apenas aonde contem o texto, tendo assim uma maior área possível de ser clicada.
![Capturar](https://user-images.githubusercontent.com/65621427/107069617-f7943880-67c0-11eb-887d-5935d6a3b63f.PNG)

**Comment by stingnelrodrigo** [comment]
Para exemplificar melhor: Unidade 2 tela 6. Podemos tomar essa como padrão.
![Capturar](https://user-images.githubusercontent.com/65621427/107072974-80ad6e80-67c5-11eb-8be5-96d66bcf0d63.PNG)

**Comment by rogergomes** [comment]
Concordo. Irei adaptar o código ou usar o padrão da outra página nessa.

**Comment by rogergomes** [comment]
Resolvido.
