### ISSUE TITLE
Unidade_2_tela_4_Barra de Áudio

### ISSUE THREAD

**Issue by stingnelrodrigo** [wendellbg/projetomooc#17]
Para cada ano clicado a barra de audio se move, não tendo alinhamento e muitas vezes fora das margens.
Pode ser notados nas imagens a seguir: 
Anos 70:
![70](https://user-images.githubusercontent.com/65621427/107070786-85245800-67c2-11eb-9ed1-c66c723effbc.PNG)

Anos 80: 
![anos 80](https://user-images.githubusercontent.com/65621427/107070874-a9803480-67c2-11eb-9eb2-63f14edbaf6d.PNG)

Anos 90:
![90](https://user-images.githubusercontent.com/65621427/107070991-d3d1f200-67c2-11eb-92c7-b6f756f33035.PNG)

**Comment by rogergomes** [comment]
Rodrigo, qual navegador está usando?
Testei aqui no safari e chrome e isso não ocorreu.
