### ISSUE TITLE
MENU Apresentação

### ISSUE THREAD

**Issue by stingnelrodrigo** [wendellbg/projetomooc#2]
No menu Apresentação da Unidade _1 tela 06 sem nome.
![1](https://user-images.githubusercontent.com/65621427/106745089-66299880-65ff-11eb-8c6a-9319c2a732d6.PNG)

No menu Apresentação da Unidade _5 telas 03 e 05 sem nome.
![2](https://user-images.githubusercontent.com/65621427/106745687-3b8c0f80-6600-11eb-9051-86e08bc39146.PNG)

**Comment by rogergomes** [comment]
Feito
