### ISSUE TITLE
Mooc2 - Uni 2- Tela 09

### ISSUE THREAD

**Issue by rogergomes** [wendellbg/projetomooc#28]
@wendellbg 
Corrigir o padrão da caixa de material complementar. 
E também inserir o botão de "acessar" dentro da caixa no lugar do link.
https://wendellbg.github.io/projetomooc/mod2/uni2/tela09.html

Usar como base:
https://wendellbg.github.io/projetomooc/mod1/uni1/tela05.html

**Comment by wendellbg** [comment]
Atualizei o arquivo CSS e o código HTML de acordo com a sugestão.

**Comment by wendellbg** [comment]
Resolvido.
