### ISSUE TITLE
Mooc 2 - uni 3 - Tela 02

### ISSUE THREAD

**Issue by rogergomes** [wendellbg/projetomooc#35]
https://wendellbg.github.io/projetomooc/mod2/uni3/tela02.html

Colocar legenda nas fotos.

Transformar a arte "OBRA" em HTML usando recurso novo ou já utilizado anteriormente.

**Comment by wendellbg** [comment]
A legenda foi inserida, estou trabalhando na arte obra para obter zoom de cada quadro separadamente.
