### ISSUE TITLE
Caixa - Fique por dentro 

### ISSUE THREAD

**Issue by caroldesanti** [wendellbg/projetomooc#6]
Acrescentar o gif do ícone e título na caixa "fique por dentro" em:

**UNIDADE 2_Tela 5**
![05](https://user-images.githubusercontent.com/78487775/106759548-a4c84e80-6611-11eb-933f-87d14c5037f5.jpg)

**UNIDADE 4 _ Tela 4**
rever também tamanho da caixa em relação ao texto
![1](https://user-images.githubusercontent.com/78487775/106761688-d9d5a080-6613-11eb-8148-6a4ac6c19265.jpg)

**Comment by rogergomes** [comment]
Corrigido o padrão da caixa e inserido o título. Aguardando nova imagem do gif para alterar.

**Comment by rogergomes** [comment]
feito
