### ISSUE TITLE
Caixa - Atenção

### ISSUE THREAD

**Issue by caroldesanti** [wendellbg/projetomooc#8]
Acrescentar o gif do ícone e título na caixa "atenção"

**UNIDADE 3 _ Tela 3**
![07](https://user-images.githubusercontent.com/78487775/106760038-25874a80-6612-11eb-897f-d5ddd59faa1d.jpg)

**UNIDADE 4_ Tela 3**
![13](https://user-images.githubusercontent.com/78487775/106761527-abf05c00-6613-11eb-9a24-85f1c1cdb488.jpg)]

**UNIDADE 4 _ Tela 4**
![17](https://user-images.githubusercontent.com/78487775/106762354-84e65a00-6614-11eb-9ba9-99ec12efda35.jpg)

**Comment by rogergomes** [comment]
Corrigido o padrão da caixa e inserido o título. Aguardando nova imagem do gif para alterar.

**Comment by rogergomes** [comment]
feito
