### ISSUE TITLE
Trocar figura/UNIDADE 3 _ Tela 4

### ISSUE THREAD

**Issue by caroldesanti** [wendellbg/projetomooc#9]
Trocar essa figura:
![08](https://user-images.githubusercontent.com/78487775/106760215-51a2cb80-6612-11eb-90ec-f4fe87cda438.jpg)

Por essa aqui
![Infografico-00](https://user-images.githubusercontent.com/78487775/106760404-844cc400-6612-11eb-9742-46978a4c4a5a.jpg)
[https://drive.google.com/file/d/1h_ThludkFRVB6rztgKxVHo2-oxw26s7e/view?usp=sharing](url)

**Comment by rogergomes** [comment]
Feito.
